### PR TITLE
[BFW-6223] Closes #3870 - improve nozzle diameter footer item

### LINKED ISSUE #3870: [BFW-6223] [BUG] Footer nozzle size showing one decimal digit only
**Printer type** - MK4

**Printer firmware version** - 6.0.0-RC1

**Describe the bug**
Footer nozzle size info shows only one decimal digit making 0.25 mm nozzle show as 0.2 mm

**How to reproduce**
Set Hardware > Nozzle size as 0.25 mm

**Expected behavior**
Footer nozzle size info should show 2 decimal digits

### PR DESCRIPTION
**Pull request by jakubtkadlecek**
I have found 

https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/3870

quite distracting during nozzle changes, due to footer item number not corresponding to actual inputted number. Touch version of nozzle diameter input autocorrection feature as well as nozzle diameter warning check in combination with truncated number can in case of mismatch add to confusion.

I have dropped original 'g' formatting in favour of fixed decimal places and manual zero and decimal point removal, since I don't think this is easily achievable otherwise. Appending of dimensions looks a bit iffy, but the use-case seemed like overkill for StringBuilder. Usage of buffer fill could be avoided by testing for 'm' character in the cleaning loop, but results was IMO less understandable. 

0.25
nozzle_0_25

0.40
nozzle_0_4

1.00
nozzle_1

1.05
nozzle_1_05

1.10
nozze_1_1

### CODE REVIEW

**Review by CZDanol — CHANGES_REQUESTED** [review]
Please have a look at StringBuilder::append_float. It should do what you want to and using it would make the code more readable.

**Comment by jakubtkadlecek** [comment]
Indeed it does. Thanks for taking the time @CZDanol!

**Review by CZDanol — APPROVED** [review]

File: src/gui/footer/footer_items_nozzle_bed.cpp [hunk 1]
```diff
@@ -252,10 +254,12 @@ string_view_utf8 FooterItemNozzleDiameter::static_makeView(float value) {
...
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wformat-truncation"
-    snprintf(buff.data(), buff.size(), "%.1gmm", (double)value);
+    StringBuilder b(buff);
+    b.append_float((double)value, { .max_decimal_places = nozzle_diameter_spin_config.max_decimal_places, .skip_zero_before_dot = true });
+    b.append_string("mm");
 #pragma GCC diagnostic pop
 
-    return string_view_utf8::MakeRAM((const uint8_t *)(buff.data() + (buff[0] == '0' ? 1 : 0) /* if value ~ 0.xx, skip the 0 */));
+    return string_view_utf8::MakeRAM((const uint8_t *)(buff.data()));
```
Comment (CZDanol) [inline src/gui/footer/footer_items_nozzle_bed.cpp:262]: Nitpick: that cast to uint8_t is no longer needed :)

File: src/gui/footer/footer_items_nozzle_bed.cpp [hunk 2]
```diff
@@ -252,10 +254,12 @@ string_view_utf8 FooterItemNozzleDiameter::static_makeView(float value) {
 
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wformat-truncation"
```
Comment (CZDanol) [inline src/gui/footer/footer_items_nozzle_bed.cpp:256]: Nitpick: This GCC formatting is no longer needed as well

**Comment by CZDanol** [comment]
Nice, thanks :) I will try to not forget merge it tomorrow. Feel free to remind me.

**Comment by CZDanol** [comment]
Internal ticket: BFW-6223

**Comment by jakubtkadlecek** [comment]
Hey @CZDanol! I have addressed nitpicks in the latest commit.

**Comment by CZDanol** [comment]
Thanks, good job :) I'm waiting for the second approval within the team - then I'll to the merge.

**Review by CZDanol — APPROVED** [review]
